### ISSUE TITLE
GEX/DEX charts - part of numbers hidden if price is over 4 digits

### ISSUE THREAD

**Issue by tddschn** [mnsrulz/mytradingview#95]
Thanks for making this incredible tool!

TPL is trading at ~1500 and when I look up the DEX chart, part of the numbers are hidden:

https://mztrading.netlify.app/options/analyze/tpl?showDexGex=true&dgextab=DEX&sc=200

![CleanShot-2024-11-21-18 50 45](https://github.com/user-attachments/assets/8b7b0505-6032-4706-a194-c1d691f8c2fc)

**Comment by mnsrulz** [comment]
> Thanks for making this incredible tool!
> 
> TPL is trading at ~1500 and when I look up the DEX chart, part of the numbers are hidden:
> 
> https://mztrading.netlify.app/options/analyze/tpl?showDexGex=true&dgextab=DEX&sc=200
> 
> ![CleanShot-2024-11-21-18 50 45](https://private-user-images.githubusercontent.com/45612704/388735355-8b7b0505-6032-4706-a194-c1d691f8c2fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNDYyNTQsIm5iZiI6MTczMjI0NTk1NCwicGF0aCI6Ii80NTYxMjcwNC8zODg3MzUzNTUtOGI3YjA1MDUtNjAzMi00NzA2LWExOTQtYzFkNjkxZjhjMmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDAzMjU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyYjljZWQ4MmYzZjM0MzAzMjAyNmQyOWY0M2I2ZWE2ZjliYzQyMmIzMTMwZTVlMWM3ODg4NTIxOTRjMzhiYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eqB-K39W2wz4pB9BCGQGm9jtU7bfgIezx6D1_05pcUw)

fixed in the latest push
